"""Add like and comment columns to Post

Revision ID: 7355a8a1b2d8
Revises: a04e0171536b
Create Date: 2024-09-05 07:10:03.433168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7355a8a1b2d8'
down_revision = 'a04e0171536b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('like')

    # ### end Alembic commands ###
